### ISSUE TITLE
todo list

### ISSUE THREAD

**Issue by sofiebudman** [sofiebudman/CTE-Computer-Science-10th-#1]
- [ ] add drawing for building, sign, mailboc
- [ ] add drawings up the mailbox and sign messages
- [ ] add drawing of diamond
- [x] add a death screen message
- [x] add another while loop, restructer how game is played possible?
- [x] 2 more flags
- [x] another while loop, different type
- [x] another for loop (drawing)?

**Comment by sofiebudman** [comment]
done
